name       : obs-studio
version    : 0.16.1
release    : 23
source     :
    - https://github.com/jp9000/obs-studio/archive/0.16.1.tar.gz : d69d4a883fcc5d92ff9dd856bdb0aabb4aa840d809c71bed8b96482b852f6553
license    : GPL-2.0
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
setup      : |
    %cmake -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
