name       : obs-studio
version    : 23.0.1
release    : 58
source     :
    - https://github.com/obsproject/obs-studio/archive/23.0.1.tar.gz : 3230e17b6ac4be18bc6d17beaf0b8bab34a296054cbfb642c4e11df44ebfff88
license    : GPL-2.0
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(luajit)
    - pkgconfig(python3)
    - pkgconfig(speexdsp)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
    - mbedtls-devel
    - swig
setup      : |
    %cmake -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
