name       : obs-studio
version    : 21.0.0
release    : 45
source     :
    - https://github.com/jp9000/obs-studio/archive/21.0.0.tar.gz : 52ca557fd3167550750180b57db67d177d5adf6d50c4171a024060027fa7ef10
license    : GPL-2.0
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(luajit)
    - pkgconfig(python3)
    - pkgconfig(speexdsp)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
    - swig
setup      : |
    %cmake -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
