name       : obs-studio
version    : 25.0.4
release    : 71
source     :
    - https://github.com/obsproject/obs-studio/archive/25.0.4.tar.gz : c8db224d2ee4d9b91448be9e47414398e570eebe4a59ff9fd19b066789d1ccdb
license    : GPL-2.0
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(luajit)
    - pkgconfig(python3)
    - pkgconfig(speexdsp)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
    - mbedtls-devel
    - swig
setup      : |
    %cmake -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
