name       : obs-studio
version    : 23.1.0
release    : 61
source     :
    - https://github.com/obsproject/obs-studio/archive/23.1.0.tar.gz : cbaaf54864d84b9e178e87a23d06e37f9f1d91fc4f3787f7ff7673bc7dfa09d3
license    : GPL-2.0
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(luajit)
    - pkgconfig(python3)
    - pkgconfig(speexdsp)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
    - mbedtls-devel
    - swig
setup      : |
    %cmake -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
