name       : obs-studio
version    : '26.1.2'
release    : 80
source     :
    - git|https://github.com/obsproject/obs-studio.git : 26.1.2
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(luajit)
    - pkgconfig(python3)
    - pkgconfig(speexdsp)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
    - cef-minimal-devel
    - mbedtls-devel
    - swig
setup      : |
    %patch -p1 < $pkgfiles/0001-libobs-Add-function-to-get-module-lib.patch
    pushd plugins/obs-browser
    git checkout 51bf1e810f7433dbf4d4237ad3fc9aff8d841169
    %patch -p1 < $pkgfiles/obs-browser-main.patch
    %patch -p1 < $pkgfiles/0001-Revert-Render-as-linear-SRGB.patch
    %patch -p1 < $pkgfiles/0001-Revert-Expose-new-Virtualcam-frontend-function-signa.patch
    popd
    %cmake -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="/usr/share/cef-minimal" -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
