name       : obs-studio
version    : 0.15.2
release    : 18
source     :
    - https://github.com/jp9000/obs-studio/archive/0.15.2.tar.gz : b55ed2804699c919833ed52fce231d3f1f6c470809fe3af8c60f53ca58405d22
license    : GPL-2.0
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
component  : network.util
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
