name       : obs-studio
version    : 0.15.0
release    : 14
source     :
    - https://github.com/jp9000/obs-studio/archive/0.15.0.tar.gz : 684675a7fcb440a9427b74b7556ece86dd9b1397886a213b74cce8de2861debf
license    : GPL-2.0
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
component  : network.util
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
