name       : obs-studio
version    : 23.0.2
release    : 60
source     :
    - https://github.com/obsproject/obs-studio/archive/23.0.2.tar.gz : c322bcebde2a3cb6221aee3d30d96a287a0df2fb08f16f7f90d277cd6c9e91b5
license    : GPL-2.0
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video
    recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(luajit)
    - pkgconfig(python3)
    - pkgconfig(speexdsp)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
    - mbedtls-devel
    - swig
setup      : |
    %cmake -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
