name       : obs-studio
version    : 29.1.0
release    : 108
source     :
    - git|https://github.com/obsproject/obs-studio.git : 29.1.0
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(alsa)
    - pkgconfig(asio)
    - pkgconfig(fontconfig)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpci)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(librist)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(luajit)
    - pkgconfig(nlohmann_json)
    - pkgconfig(python3)
    - pkgconfig(speexdsp)
    - pkgconfig(srt)
    - pkgconfig(libvlc)
    - pkgconfig(wayland-client)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon-x11)
    - cef-minimal-devel
    - mbedtls-devel
    - swig
    - websocketpp
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-Werror.patch
    %cmake_ninja \
        -DBUILD_BROWSER=ON \
        -DCEF_ROOT_DIR="/usr/share/cef-minimal" \
        -DENABLE_AJA=OFF \
        -DOBS_VERSION_OVERRIDE="$version" solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
