name       : obs-studio
version    : 0.15.4
release    : 21
source     :
    - https://github.com/jp9000/obs-studio/archive/0.15.4.tar.gz : e0ea4f6c25e8b101902c057332bdb47dc4e6c6ce4fce0c2411d7a17b25987885
license    : GPL-2.0
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
component  : multimedia.video
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
setup      : |
    %cmake -DOBS_VERSION_OVERRIDE="$version" .
build      : |
    %make
install    : |
    %make_install
