name       : obs-studio
version    : 0.13.1
release    : 8
source     :
    - https://github.com/jp9000/obs-studio/archive/0.13.1.tar.gz : 59f82824b94e9c832f4a62b76ec5892774c70b1bfdcd646c96bcb9cf472656ef
license    : GPL-2.0
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit: no
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
