name       : obs-studio
version    : 0.12.2
release    : 5
source     :
    - https://github.com/jp9000/obs-studio/archive/0.12.2.tar.gz : 5d78f11e7bd63c793c61f56587e79c3f7b3e2958ad87f7be90f0e272a4bdc381
license    : GPL-2.0
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit: no
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse)
    - pkgconfig(libv4l2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xinerama)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
